const types = {
  LOGIN_REQUEST: 'SERVICES/LOGIN_REQUEST',
  LOGIN_SUCCESS: 'SERVICES/LOGIN_SUCCESS',
  LOGIN_FAILURE: 'SERVICES/LOGIN_FAILURE',

  SIGNUP_REQUEST: 'SERVICES/SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'SERVICES/SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SERVICES/SIGNUP_FAILURE',
};

export default types;
